spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework2?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: root
    password: cz_hyy6848

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
