spring:
  profiles:
    include: aws

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
